// packages/vue/src/components/LDesignMap.vue
<template>
  <div ref="mapContainer" class="ldesign-map" :style="containerStyle">
    <div v-if="loading" class="ldesign-map__loading">
      <slot name="loading">加载中...</slot>
    </div>
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { 
  ref, 
  onMounted, 
  onUnmounted, 
  computed, 
  watch, 
  provide,
  shallowRef
} from 'vue';
import { 
  MapRenderer,
  LayerManager,
  AnimationController,
  EventManager,
  type MapOptions,
  type LayerOptions 
} from '@ldesign-map/core';

// Props 定义
const props = withDefaults(defineProps<{
  width?: string | number;
  height?: string | number;
  options?: MapOptions;
  layers?: LayerOptions[];
  viewState?: any;
  interactive?: boolean;
}>(), {
  width: '100%',
  height: '400px',
  interactive: true
});

// Emits 定义
const emit = defineEmits<{
  ready: [map: MapRenderer];
  click: [info: any];
  hover: [info: any];
  viewChange: [viewState: any];
  layerAdd: [layerId: string];
  layerRemove: [layerId: string];
  layerUpdate: [layerId: string];
  error: [error: Error];
}>();

// Refs
const mapContainer = ref<HTMLElement>();
const loading = ref(true);
const mapInstance = shallowRef<MapRenderer>();
const layerManager = shallowRef<LayerManager>();
const animationController = shallowRef<AnimationController>();
const eventManager = shallowRef<EventManager>();

// Computed
const containerStyle = computed(() => ({
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height
}));

// 初始化地图
const initMap = async () => {
  if (!mapContainer.value) return;

  try {
    // 创建地图实例
    mapInstance.value = new MapRenderer(mapContainer.value, {
      ...props.options,
      interactive: props.interactive
    });

    // 创建管理器
    layerManager.value = new LayerManager(mapInstance.value);
    animationController.value = new AnimationController(mapInstance.value);
    eventManager.value = new EventManager();

    // 设置事件监听
    setupEventListeners();

    // 添加初始图层
    if (props.layers) {
      props.layers.forEach(layer => {
        layerManager.value!.addLayer(layer);
      });
    }

    // 设置初始视图状态
    if (props.viewState) {
      mapInstance.value.setViewState(props.viewState);
    }

    loading.value = false;
    emit('ready', mapInstance.value);
  } catch (error) {
    console.error('Failed to initialize map:', error);
    loading.value = false;
    emit('error', error as Error);
  }
};

// 设置事件监听器
const setupEventListeners = () => {
  if (!mapInstance.value) return;

  mapInstance.value.on('click', (info: any) => {
    emit('click', info);
  });

  mapInstance.value.on('hover', (info: any) => {
    emit('hover', info);
  });

  mapInstance.value.on('viewStateChange', (viewState: any) => {
    emit('viewChange', viewState);
  });
};

// Watch props 变化
watch(() => props.layers, (newLayers) => {
  if (!layerManager.value || !newLayers) return;
  
  // 清除现有图层
  layerManager.value.clear();
  
  // 添加新图层
  newLayers.forEach(layer => {
    layerManager.value!.addLayer(layer);
  });
}, { deep: true });

watch(() => props.viewState, (newViewState) => {
  if (!mapInstance.value || !newViewState) return;
  mapInstance.value.setViewState(newViewState);
}, { deep: true });

// 公开的方法
const addLayer = (options: LayerOptions): string => {
  if (!layerManager.value) throw new Error('Map not initialized');
  const layerId = layerManager.value.addLayer(options);
  emit('layerAdd', layerId);
  return layerId;
};

const removeLayer = (layerId: string): boolean => {
  if (!layerManager.value) throw new Error('Map not initialized');
  const result = layerManager.value.removeLayer(layerId);
  if (result) emit('layerRemove', layerId);
  return result;
};

const updateLayer = (layerId: string, updates: Partial<LayerOptions>): boolean => {
  if (!layerManager.value) throw new Error('Map not initialized');
  const result = layerManager.value.updateLayer(layerId, updates);
  if (result) emit('layerUpdate', layerId);
  return result;
};

const flyTo = (options: {
  longitude: number;
  latitude: number;
  zoom?: number;
  duration?: number;
}): void => {
  if (!animationController.value) throw new Error('Map not initialized');
  animationController.value.flyTo(options);
};

const getViewState = (): any => {
  if (!mapInstance.value) throw new Error('Map not initialized');
  return mapInstance.value.getViewState();
};

const setViewState = (viewState: any): void => {
  if (!mapInstance.value) throw new Error('Map not initialized');
  mapInstance.value.setViewState(viewState);
};

// 提供给子组件的注入
provide('mapInstance', mapInstance);
provide('layerManager', layerManager);
provide('animationController', animationController);

// 生命周期
onMounted(() => {
  initMap();
});

onUnmounted(() => {
  if (eventManager.value) {
    eventManager.value.removeAll();
  }
  if (layerManager.value) {
    layerManager.value.destroy();
  }
  if (animationController.value) {
    animationController.value.destroy();
  }
  if (mapInstance.value) {
    mapInstance.value.destroy();
  }
});

// 暴露给父组件的方法
defineExpose({
  addLayer,
  removeLayer,
  updateLayer,
  flyTo,
  getViewState,
  setViewState,
  mapInstance,
  layerManager,
  animationController
});
</script>

<style scoped>
.ldesign-map {
  position: relative;
  overflow: hidden;
}

.ldesign-map__loading {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 10;
  background: rgba(255, 255, 255, 0.9);
  padding: 20px;
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
}
</style>

// packages/lit/src/ldesign-map.ts
import { LitElement, html, css, PropertyValues } from 'lit';
import { customElement, property, state, query } from 'lit/decorators.js';
import {
  MapRenderer,
  LayerManager,
  AnimationController,
  EventManager,
  type MapOptions,
  type LayerOptions
} from '@ldesign-map/core';

/**
 * LDesign Map Web Component using Lit
 * @element ldesign-map
 */
@customElement('ldesign-map')
export class LDesignMapElement extends LitElement {
  static override styles = css`
    :host {
      display: block;
      position: relative;
      width: 100%;
      height: 400px;
    }

    .map-container {
      width: 100%;
      height: 100%;
      position: relative;
      overflow: hidden;
    }

    .loading {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background: rgba(255, 255, 255, 0.9);
      padding: 20px;
      border-radius: 4px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
      z-index: 10;
    }

    ::slotted(*) {
      position: relative;
      z-index: 1;
    }
  `;

  // Properties
  @property({ type: Number }) width?: number;
  @property({ type: Number }) height?: number;
  @property({ type: Object }) options?: MapOptions;
  @property({ type: Array }) layers: LayerOptions[] = [];
  @property({ type: Object }) viewState?: any;
  @property({ type: Boolean }) interactive = true;

  // State
  @state() private loading = true;

  // DOM Query
  @query('.map-container') private container!: HTMLDivElement;

  // Private properties
  private mapInstance?: MapRenderer;
  private layerManager?: LayerManager;
  private animationController?: AnimationController;
  private eventManager?: EventManager;

  constructor() {
    super();
  }

  override connectedCallback() {
    super.connectedCallback();
    // Set host dimensions if provided
    if (this.width) {
      this.style.width = `${this.width}px`;
    }
    if (this.height) {
      this.style.height = `${this.height}px`;
    }
  }

  override disconnectedCallback() {
    super.disconnectedCallback();
    this.destroy();
  }

  override firstUpdated() {
    this.initializeMap();
  }

  override updated(changedProperties: PropertyValues) {
    // Handle layers update
    if (changedProperties.has('layers') && this.layerManager) {
      this.updateLayers();
    }

    // Handle viewState update
    if (changedProperties.has('viewState') && this.mapInstance && this.viewState) {
      this.mapInstance.setViewState(this.viewState);
    }
  }

  private async initializeMap() {
    if (!this.container) return;

    try {
      // Create map instance
      this.mapInstance = new MapRenderer(this.container, {
        ...this.options,
        interactive: this.interactive
      });

      // Create managers
      this.layerManager = new LayerManager(this.mapInstance);
      this.animationController = new AnimationController(this.mapInstance);
      this.eventManager = new EventManager();

      // Setup event listeners
      this.setupEventListeners();

      // Add initial layers
      if (this.layers && this.layers.length > 0) {
        this.layers.forEach(layer => {
          this.layerManager!.addLayer(layer);
        });
      }

      // Set initial view state
      if (this.viewState) {
        this.mapInstance.setViewState(this.viewState);
      }

      this.loading = false;

      // Dispatch ready event
      this.dispatchEvent(new CustomEvent('ready', {
        detail: { map: this.mapInstance },
        bubbles: true,
        composed: true
      }));
    } catch (error) {
      console.error('Failed to initialize map:', error);
      this.loading = false;

      // Dispatch error event
      this.dispatchEvent(new CustomEvent('error', {
        detail: { error },
        bubbles: true,
        composed: true
      }));
    }
  }

  private setupEventListeners() {
    if (!this.mapInstance) return;

    this.mapInstance.on('click', (info: any) => {
      this.dispatchEvent(new CustomEvent('map-click', {
        detail: info,
        bubbles: true,
        composed: true
      }));
    });

    this.mapInstance.on('hover', (info: any) => {
      this.dispatchEvent(new CustomEvent('map-hover', {
        detail: info,
        bubbles: true,
        composed: true
      }));
    });

    this.mapInstance.on('viewStateChange', (viewState: any) => {
      this.dispatchEvent(new CustomEvent('view-change', {
        detail: viewState,
        bubbles: true,
        composed: true
      }));
    });
  }

  private updateLayers() {
    if (!this.layerManager) return;

    // Clear existing layers
    this.layerManager.clear();

    // Add new layers
    this.layers.forEach(layer => {
      const layerId = this.layerManager!.addLayer(layer);

      // Dispatch layer add event
      this.dispatchEvent(new CustomEvent('layer-add', {
        detail: { layerId },
        bubbles: true,
        composed: true
      }));
    });
  }

  // Public methods
  public addLayer(options: LayerOptions): string {
    if (!this.layerManager) throw new Error('Map not initialized');
    const layerId = this.layerManager.addLayer(options);

    this.dispatchEvent(new CustomEvent('layer-add', {
      detail: { layerId },
      bubbles: true,
      composed: true
    }));

    return layerId;
  }

  public removeLayer(layerId: string): boolean {
    if (!this.layerManager) throw new Error('Map not initialized');
    const result = this.layerManager.removeLayer(layerId);

    if (result) {
      this.dispatchEvent(new CustomEvent('layer-remove', {
        detail: { layerId },
        bubbles: true,
        composed: true
      }));
    }

    return result;
  }

  public updateLayer(layerId: string, updates: Partial<LayerOptions>): boolean {
    if (!this.layerManager) throw new Error('Map not initialized');
    const result = this.layerManager.updateLayer(layerId, updates);

    if (result) {
      this.dispatchEvent(new CustomEvent('layer-update', {
        detail: { layerId, updates },
        bubbles: true,
        composed: true
      }));
    }

    return result;
  }

  public flyTo(options: {
    longitude: number;
    latitude: number;
    zoom?: number;
    duration?: number;
  }): void {
    if (!this.animationController) throw new Error('Map not initialized');
    this.animationController.flyTo(options);
  }

  public getViewState(): any {
    if (!this.mapInstance) throw new Error('Map not initialized');
    return this.mapInstance.getViewState();
  }

  public setViewState(viewState: any): void {
    if (!this.mapInstance) throw new Error('Map not initialized');
    this.mapInstance.setViewState(viewState);
    this.viewState = viewState;
  }

  public getMapInstance(): MapRenderer | undefined {
    return this.mapInstance;
  }

  public getLayerManager(): LayerManager | undefined {
    return this.layerManager;
  }

  public getAnimationController(): AnimationController | undefined {
    return this.animationController;
  }

  private destroy() {
    if (this.eventManager) {
      this.eventManager.removeAll();
    }
    if (this.layerManager) {
      this.layerManager.destroy();
    }
    if (this.animationController) {
      this.animationController.destroy();
    }
    if (this.mapInstance) {
      this.mapInstance.destroy();
    }
  }

  override render() {
    return html`
      <div class="map-container">
        ${this.loading ? html`
          <div class="loading">
            <slot name="loading">Loading map...</slot>
          </div>
        ` : ''}
        <slot></slot>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ldesign-map': LDesignMapElement;
  }
}
