// packages/react/src/components/LDesignMap.tsx
import React, { useRef, useEffect, useState, useImperativeHandle, forwardRef, ReactNode } from 'react';
import {
  MapRenderer,
  LayerManager,
  AnimationController,
  EventManager,
  type MapOptions,
  type LayerOptions
} from '@ldesign-map/core';
import { MapContext } from '../context/MapContext';

/**
 * LDesignMap Props
 */
export interface LDesignMapProps {
  /** 容器宽度 */
  width?: string | number;
  /** 容器高度 */
  height?: string | number;
  /** 地图配置选项 */
  options?: MapOptions;
  /** 初始图层 */
  layers?: LayerOptions[];
  /** 视图状态 */
  viewState?: any;
  /** 是否可交互 */
  interactive?: boolean;
  /** 加载时显示的内容 */
  loadingComponent?: ReactNode;
  /** 子组件 */
  children?: ReactNode;
  /** 类名 */
  className?: string;
  /** 样式 */
  style?: React.CSSProperties;

  // 事件回调
  onReady?: (map: MapRenderer) => void;
  onClick?: (info: any) => void;
  onHover?: (info: any) => void;
  onViewChange?: (viewState: any) => void;
  onLayerAdd?: (layerId: string) => void;
  onLayerRemove?: (layerId: string) => void;
  onLayerUpdate?: (layerId: string) => void;
  onError?: (error: Error) => void;
}

export interface LDesignMapRef {
  addLayer: (options: LayerOptions) => string;
  removeLayer: (layerId: string) => boolean;
  updateLayer: (layerId: string, updates: Partial<LayerOptions>) => boolean;
  flyTo: (options: any) => void;
  getViewState: () => any;
  setViewState: (viewState: any) => void;
  mapInstance?: MapRenderer;
  layerManager?: LayerManager;
  animationController?: AnimationController;
}

/**
 * LDesignMap React Component
 */
export const LDesignMap = forwardRef<LDesignMapRef, LDesignMapProps>((props, ref) => {
  const {
    width = '100%',
    height = '400px',
    options,
    layers = [],
    viewState,
    interactive = true,
    loadingComponent,
    children,
    className = '',
    style = {},
    onReady,
    onClick,
    onHover,
    onViewChange,
    onLayerAdd,
    onLayerRemove,
    onLayerUpdate,
    onError
  } = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState(true);
  const [mapInstance, setMapInstance] = useState<MapRenderer>();
  const [layerManager, setLayerManager] = useState<LayerManager>();
  const [animationController, setAnimationController] = useState<AnimationController>();
  const eventManagerRef = useRef<EventManager>();

  // 初始化地图
  useEffect(() => {
    if (!containerRef.current) return;

    const initMap = async () => {
      try {
        // 创建地图实例
        const map = new MapRenderer(containerRef.current!, {
          ...options,
          interactive
        });

        // 创建管理器
        const lm = new LayerManager(map);
        const ac = new AnimationController(map);
        const em = new EventManager();

        eventManagerRef.current = em;

        // 设置事件监听
        if (onClick) {
          map.on('click', onClick);
        }
        if (onHover) {
          map.on('hover', onHover);
        }
        if (onViewChange) {
          map.on('viewStateChange', onViewChange);
        }

        // 添加初始图层
        layers.forEach(layer => {
          const layerId = lm.addLayer(layer);
          onLayerAdd?.(layerId);
        });

        // 设置初始视图状态
        if (viewState) {
          map.setViewState(viewState);
        }

        setMapInstance(map);
        setLayerManager(lm);
        setAnimationController(ac);
        setLoading(false);

        onReady?.(map);
      } catch (error) {
        console.error('Failed to initialize map:', error);
        setLoading(false);
        onError?.(error as Error);
      }
    };

    initMap();

    // 清理函数
    return () => {
      if (eventManagerRef.current) {
        eventManagerRef.current.removeAll();
      }
      if (layerManager) {
        layerManager.destroy();
      }
      if (animationController) {
        animationController.destroy();
      }
      if (mapInstance) {
        mapInstance.destroy();
      }
    };
  }, []); // 只在组件挂载时初始化一次

  // 监听图层变化
  useEffect(() => {
    if (!layerManager || !layers) return;

    // 清除现有图层
    layerManager.clear();

    // 添加新图层
    layers.forEach(layer => {
      const layerId = layerManager.addLayer(layer);
      onLayerAdd?.(layerId);
    });
  }, [layers, layerManager]);

  // 监听视图状态变化
  useEffect(() => {
    if (!mapInstance || !viewState) return;
    mapInstance.setViewState(viewState);
  }, [viewState, mapInstance]);

  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    addLayer: (options: LayerOptions) => {
      if (!layerManager) throw new Error('Map not initialized');
      const layerId = layerManager.addLayer(options);
      onLayerAdd?.(layerId);
      return layerId;
    },
    removeLayer: (layerId: string) => {
      if (!layerManager) throw new Error('Map not initialized');
      const result = layerManager.removeLayer(layerId);
      if (result) onLayerRemove?.(layerId);
      return result;
    },
    updateLayer: (layerId: string, updates: Partial<LayerOptions>) => {
      if (!layerManager) throw new Error('Map not initialized');
      const result = layerManager.updateLayer(layerId, updates);
      if (result) onLayerUpdate?.(layerId);
      return result;
    },
    flyTo: (options: any) => {
      if (!animationController) throw new Error('Map not initialized');
      animationController.flyTo(options);
    },
    getViewState: () => {
      if (!mapInstance) throw new Error('Map not initialized');
      return mapInstance.getViewState();
    },
    setViewState: (vs: any) => {
      if (!mapInstance) throw new Error('Map not initialized');
      mapInstance.setViewState(vs);
    },
    mapInstance,
    layerManager,
    animationController
  }), [mapInstance, layerManager, animationController]);

  // 容器样式
  const containerStyle: React.CSSProperties = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
    position: 'relative',
    overflow: 'hidden',
    ...style
  };

  return (
    <MapContext.Provider value={{ mapInstance, layerManager, animationController }}>
      <div
        ref={containerRef}
        className={`ldesign-map ${className}`}
        style={containerStyle}
      >
        {loading && (
          <div className="ldesign-map__loading">
            {loadingComponent || <span>Loading map...</span>}
          </div>
        )}
        {children}
      </div>
    </MapContext.Provider>
  );
});

LDesignMap.displayName = 'LDesignMap';

// packages/vue/src/components/LDesignMap.vue
<template>
  <div ref="mapContainer" class="ldesign-map" :style="containerStyle">
    <div v-if="loading" class="ldesign-map__loading">
      <slot name="loading">加载中...</slot>
    </div>
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { 
  ref, 
  onMounted, 
  onUnmounted, 
  computed, 
  watch, 
  provide,
  shallowRef
} from 'vue';
import { 
  MapRenderer,
  LayerManager,
  AnimationController,
  EventManager,
  type MapOptions,
  type LayerOptions 
} from '@ldesign-map/core';

// Props 定义
const props = withDefaults(defineProps<{
  width?: string | number;
  height?: string | number;
  options?: MapOptions;
  layers?: LayerOptions[];
  viewState?: any;
  interactive?: boolean;
}>(), {
  width: '100%',
  height: '400px',
  interactive: true
});

// Emits 定义
const emit = defineEmits<{
  ready: [map: MapRenderer];
  click: [info: any];
  hover: [info: any];
  viewChange: [viewState: any];
  layerAdd: [layerId: string];
  layerRemove: [layerId: string];
  layerUpdate: [layerId: string];
  error: [error: Error];
}>();

// Refs
const mapContainer = ref<HTMLElement>();
const loading = ref(true);
const mapInstance = shallowRef<MapRenderer>();
const layerManager = shallowRef<LayerManager>();
const animationController = shallowRef<AnimationController>();
const eventManager = shallowRef<EventManager>();

// Computed
const containerStyle = computed(() => ({
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height
}));

// 初始化地图
const initMap = async () => {
  if (!mapContainer.value) return;

  try {
    // 创建地图实例
    mapInstance.value = new MapRenderer(mapContainer.value, {
      ...props.options,
      interactive: props.interactive
    });

    // 创建管理器
    layerManager.value = new LayerManager(mapInstance.value);
    animationController.value = new AnimationController(mapInstance.value);
    eventManager.value = new EventManager();

    // 设置事件监听
    setupEventListeners();

    // 添加初始图层
    if (props.layers) {
      props.layers.forEach(layer => {
        layerManager.value!.addLayer(layer);
      });
    }

    // 设置初始视图状态
    if (props.viewState) {
      mapInstance.value.setViewState(props.viewState);
    }

    loading.value = false;
    emit('ready', mapInstance.value);
  } catch (error) {
    console.error('Failed to initialize map:', error);
    loading.value = false;
    emit('error', error as Error);
  }
};

// 设置事件监听器
const setupEventListeners = () => {
  if (!mapInstance.value) return;

  mapInstance.value.on('click', (info: any) => {
    emit('click', info);
  });

  mapInstance.value.on('hover', (info: any) => {
    emit('hover', info);
  });

  mapInstance.value.on('viewStateChange', (viewState: any) => {
    emit('viewChange', viewState);
  });
};

// Watch props 变化
watch(() => props.layers, (newLayers) => {
  if (!layerManager.value || !newLayers) return;
  
  // 清除现有图层
  layerManager.value.clear();
  
  // 添加新图层
  newLayers.forEach(layer => {
    layerManager.value!.addLayer(layer);
  });
}, { deep: true });

watch(() => props.viewState, (newViewState) => {
  if (!mapInstance.value || !newViewState) return;
  mapInstance.value.setViewState(newViewState);
}, { deep: true });

// 公开的方法
const addLayer = (options: LayerOptions): string => {
  if (!layerManager.value) throw new Error('Map not initialized');
  const layerId = layerManager.value.addLayer(options);
  emit('layerAdd', layerId);
  return layerId;
};

const removeLayer = (layerId: string): boolean => {
  if (!layerManager.value) throw new Error('Map not initialized');
  const result = layerManager.value.removeLayer(layerId);
  if (result) emit('layerRemove', layerId);
  return result;
};

const updateLayer = (layerId: string, updates: Partial<LayerOptions>): boolean => {
  if (!layerManager.value) throw new Error('Map not initialized');
  const result = layerManager.value.updateLayer(layerId, updates);
  if (result) emit('layerUpdate', layerId);
  return result;
};

const flyTo = (options: {
  longitude: number;
  latitude: number;
  zoom?: number;
  duration?: number;
}): void => {
  if (!animationController.value) throw new Error('Map not initialized');
  animationController.value.flyTo(options);
};

const getViewState = (): any => {
  if (!mapInstance.value) throw new Error('Map not initialized');
  return mapInstance.value.getViewState();
};

const setViewState = (viewState: any): void => {
  if (!mapInstance.value) throw new Error('Map not initialized');
  mapInstance.value.setViewState(viewState);
};

// 提供给子组件的注入
provide('mapInstance', mapInstance);
provide('layerManager', layerManager);
provide('animationController', animationController);

// 生命周期
onMounted(() => {
  initMap();
});

onUnmounted(() => {
  if (eventManager.value) {
    eventManager.value.removeAll();
  }
  if (layerManager.value) {
    layerManager.value.destroy();
  }
  if (animationController.value) {
    animationController.value.destroy();
  }
  if (mapInstance.value) {
    mapInstance.value.destroy();
  }
});

// 暴露给父组件的方法
defineExpose({
  addLayer,
  removeLayer,
  updateLayer,
  flyTo,
  getViewState,
  setViewState,
  mapInstance,
  layerManager,
  animationController
});
</script>

<style scoped>
.ldesign-map {
  position: relative;
  overflow: hidden;
}

.ldesign-map__loading {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 10;
  background: rgba(255, 255, 255, 0.9);
  padding: 20px;
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
}
</style>
